### ISSUE TITLE
unauthenticated git doesn't work anymore

### ISSUE THREAD

**Issue by abiggerhammer** [JustinSDK/cqMore#1]
Your README says to install with `pip install git+git://github.com/JustinSDK/cqMore`, but this no longer works because github [permanently disabled unauthenticated git](https://github.blog/2021-09-01-improving-git-protocol-security-github/) about a month ago. `git+https://github.com/JustinSDK/cqMore` works fine, though.

**Comment by JustinSDK** [comment]
Thanks for your remind. Updated.
